name: Publish package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publishPackage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build
      - name: Bump version
        run: |
          git config --global user.name 'Neogma publisher'
          git config --global user.email 'themetalfleece@users.noreply.github.com'
          npm version ${{ inputs.version }}
      - name: Publish to npm
        run: npm publish
      - name: Push
        run: git push
      - name: Push tags
        run: git push --tags
